### PR TITLE
add option to only load starfile parameters in RelionDataset

### PR DESCRIPTION
**Pull request by DSilva27**

### CODE REVIEW

**Comment by mjo22** [comment]
Great. I'll look through this and see if there are any touchups to add. One small thing is that calling a method `__mymethod__` is convention for a python magic method (a method in `object` that has special functionality), like `__getitem__`, `__mul__`, `__len__`, etc. I would rename the other methods to a private method convention, like `_mymethod`.

**Comment by DSilva27** [comment]
Names changed.

**Comment by mjo22** [comment]
Just pushed some small changes

**Review by mjo22 — APPROVED** [review]

**Comment by DSilva27** [comment]
I can create a starfile with a couple of very small particles. Maybe 5 particles of size 8x8.

**Comment by mjo22** [comment]
That would be awesome thank you... just added option to read JAX arrays on the CPU. This should avoid array copying when using the torch dataloader, but haven't confirmed this for sure.

**Comment by mjo22** [comment]
We can go ahead and merge I think. Can continue to work on tests

**Pull request merged**
