### PR TITLE
Simulate xyz

### PR DESCRIPTION
**Pull request by ehthiede**
Second draft of the atomic structure to density code, hopefully the conventions are compatible now.  Loading into VoxelGrids should now be supported as well, as should loading from .cif files.

Some notes:

- There are a few unnecessary calls where I regenerate coordinate systems that already exist: eventually this will be refactored out, but for now I prioritized functioning over clean.
- Naming conventions should be revisited pending conclusion of #91 .
- I did have to make a minor change in the fft code since .dim doesn't work for jax's compiled ArrayImpl object.  Hopefully this didn't break anything elsewhere.

### CODE REVIEW

**Review by mjo22 — APPROVED** [review]
This looks fantastic. 

On the .dim issue: this was a bug on my part. This should have said ft.ndim and ift.ndim—your `dim = len(ft.shape)` does the same. I actually don’t use the rfftn and irfftn routines in the code anywhere yet, I just added these recently because of plans to eventually make things more memory-conservative.

One question this is making me have—what do you think about `Voxels.from_file`? This routine could be kept if we had some logic that chose a loader based on the file extension. Another route would be to just get rid of it all together.

Also, what do you think about the abstract methods and dataclass fields in the `Voxels` base class? For one, #91 means removing the “coordinates” AbstractVar. The only benefit of having these AbstractVars is if external objects should expect something like “weights” to be a field of something where isinstance(density, Voxels) is True. Right now, we could go either way, but in general these AbstractVars are a useful pattern for type checkers and developers.

For another, `Voxels.from_mrc` is an abstract method but other loaders are not. Should other loaders be added as abstract methods, or does it make sense as is?

We can definitely merge. We should resolve #91 before merging into main.

**Comment by mjo22** [comment]
Another comment: it’s a little weird that I create instantiation dicts in load_voxels.py. I like that the new constructors don’t do this. In general, the load_voxels.py and from_mrc constructors should be rethought a little I think. We should update these as well?

**Comment by ehthiede** [comment]
Thanks for the comments! I'm going to try and refactor the code to go with `coordinate_grid/plane/list` and then merge into `simulate_xyz`.  We can change the nomenclature to something else later, but having my names be more descriptive than they are right now should help with later refactorings.

Would you be ok with merging to main after that?  I'm a little worried about our branches drifting too far apart.  Alternatively, if you want to protect main a little more, we could start a develop branch: your call.

**Comment by mjo22** [comment]
Yes this sounds good and let’s merge into main after this. Also, let’s just worry about the 3D coordinates for now—this shouldn’t break much in the code. For this, each of the VoxelGrid, VoxelCloud, FourierSliceExtract, and NufftProject will need to be modified. I don’t think anything else. I can go through renaming the 2D coordinate systems later, which will break more in the code (unless you would like to do so!).

**Pull request merged**
